bl_form:
    resource: "@BLFormBundle/Resources/config/routing.yml"
    prefix:   /

#bl_formulaires:
#    resource: "@BlFormulairesBundle/Resources/config/routing.yml"
#    prefix:   /

#bl_forms:
#    resource: "@BLFormsBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

page_accueil:
    path:   /accueil
    defaults:   {_controller: AppBundle:Controller:Default}
    requirements:
        page: '\d+'

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }