<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container93pvyi2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container93pvyi2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container93pvyi2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container93pvyi2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container93pvyi2\appDevDebugProjectContainer(array(
    'container.build_hash' => '93pvyi2',
    'container.build_id' => '63e18aab',
    'container.build_time' => 1516719284,
));
