<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdx6trp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdx6trp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYdx6trp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYdx6trp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYdx6trp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ydx6trp',
    'container.build_id' => '16d5b183',
    'container.build_time' => 1516101211,
));
