<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9rnnstf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9rnnstf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9rnnstf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9rnnstf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9rnnstf\appDevDebugProjectContainer(array(
    'container.build_hash' => '9rnnstf',
    'container.build_id' => 'f14ade35',
    'container.build_time' => 1516110601,
));
